### ISSUE TITLE
Check if user is authenticated

### ISSUE THREAD

**Issue by depuits** [milesbarr/mongoose-user-auth#1]
How is it possible to know when a user is authenticated? The example code shows how to check for an error, existing user and locked. After that the example just says you're authenticated without actually checking if the password was correct.

By checking the code I can see that the password is checked but after increasing the number of login attempts it just returns the user without setting a flag anywhere to let know if the login is actually successful. 

```
if (!isMatch) {
	user.incAuthAttempts(function (err) {
		if (err) {
			cb(err);
		} else {
			cb(null, user); // after increasing the login attempts successful the user is still just returned without error, making it impossible to know if the authentication is actually succesfull
		}
	});
	return;
}
```

**Comment by milesbarr** [comment]
Hi, you are correct. That is fixed with this commit: https://github.com/milesbarr/mongoose-user-auth/commit/b2d350979cf2438aad0f21c0daa80728ddff84c6.

**Comment by depuits** [comment]
I was just working on unit tests to solve the problem :) The readme should still be updated to say if the user is null and the error is null then the password was incorrect.

**Comment by depuits** [comment]
Though not needed for my use case, now there isn't a way to determine if the user doesn't exists or the password was incorrect.

**Comment by milesbarr** [comment]
I intentionally left out the ability to check whether a user exists or entered an incorrect password since most sites prefer to hide that for security reasons. However, if you feel it could be useful, then I have no problem merging that functionality. Thank you for the contribution.
